config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :lists, only: [:index, :show, :create] do
    resources :bookmarks, only: [:new, :create]
  end
  resources :bookmarks, only: [:destroy]
  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :list
  belongs_to :movie
  validates :list_id, uniqueness: {scope: :movie_id}
  validates :comment, length: { minimum: 6 }
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks, dependent: :destroy # bookmark sont détruits si list détruite
  has_many :movies, through: :bookmarks
  validates :name, uniqueness: true, presence: true
  has_one_attached :photo
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks
  has_many :lists, through: :bookmarks
  validates :title, uniqueness: true, presence:true 
  validates :overview, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  def new
    @list = List.find(params[:list_id])
    @bookmark = Bookmark.new
  end

  def create
  @list = List.find(params[:list_id])
  @bookmark = Bookmark.new(bookmark_params)
  @bookmark.list = @list
  @bookmark.save
  redirect_to list_path(@list)
  end

  def destroy
    @bookmark = Bookmark.find(params[:id])
    @bookmark.destroy
    redirect_to list_path(@bookmark.list), status: :see_other
  end

  private
  def bookmark_params
    params.require(:bookmark).permit(:comment, :movie_id, :list_id)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def index
    @lists = List.all
    @list = List.new
  end

  def show
    @list = List.find(params[:id])
  end

  def create
    @list = List.new(list_params)
    @list.save
    redirect_to lists_path
  end

  private
  def list_params
    params.require(:list).permit(:name, :photo)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/bookmarks/new.html.erb
<h1>Add a movie to <%= @list.name %> list</h1>
<%= simple_form_for [@list, @bookmark] do |f| %>
    <%= f.association :movie, as: :select %>
    <%= f.input :comment %>
  <%= f.submit "Add to this list", class: "btn btn-primary" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lists/index.html.erb
<div class="container py-5">
<h1>Lists</h1>
<div class="cards">
  <% @lists.each do |list| %>
  <% if list.photo.attached? %>
        <div class="card-category" style="background-image: url(<%= cl_image_path(list.photo.key)%>)">
    <% else %>
    <div class="card-category" style="background-color: black">
    <% end %>
          <%= link_to list.name, list_path(list) %>
        </div>
  <% end %>
</div>



<%= simple_form_for(@list) do |f| %>
  <%= f.input :name %>
    <%= f.input :photo, as: :file %>
  <%= f.submit class:"btn btn-primary" %>
<% end %>
</div>


<%# style="background-image: url(<%= cl_image_path(list.photo.key)%>

app/views/lists/show.html.erb
<%# <%= cl_image_tag(@list.photo.key),
      width: 400, height: 300, crop: :fill %>
    <%= console  %>

<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(<%= cl_image_path(@list.photo.key)%>);">
  <div class="container">
    <p><%= @list.name %></p>


  </div>
</div>



  <ul>
  <% @list.movies.each do |movie| %>
    <li>
      <% bookmark = Bookmark.find_by(list: @list, movie: movie) %>
      <%= movie.title %>
      <p><%= link_to "Delete", bookmark_path(bookmark), data: {turbo_method: :delete, turbo_confirm: "Noemie ok ?"} %></p>
    </li>
  <% end %>
  </ul>
  <p><%= link_to "Add a movie", new_list_bookmark_path(@list)%></p>